version: "3.5"

services:

  app:
    build:
      target: develop
      args:
        XDEBUG_REMOTE_HOST: ${XDEBUG_REMOTE_HOST:-127.0.0.1}
    volumes:
      - ./app:/app

  nginx:
    build:
      target: develop
    command: [ nginx-debug, '-g', 'daemon off;' ]
    environment:
      - NGINX_HOST=my.laravel.dev
      - NGINX_PORT=80
    volumes:
      - ./app:/app
    ports:
      - "80:80"

  mysql:
    volumes:
      - ./mysql/data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    ports:
      - "82:80"
    environment:
      - PMA_HOST=mysql
      - PMA_USER=${DATABASE_USER}
      - PMA_PASSWORD=${DATABASE_PASSWORD}
